Corrigir rotas para o método POST em UserController
matheus-yudi-newrizon/review-reveal-api pull request #10
Opened 2023-10-24 19:19 UTC by HebertFSoares

2023-10-24 19:19 UTC, HebertFSoares commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BACK] Corrigir rotas](https://trello.com/c/yBL1zzSI/331-back-corrigir-rotas)

2023-10-25 02:05 UTC, dairsposito requested changes

2023-10-25 02:05 UTC, dairsposito commented on src/routes.ts
> +router.get('/signup', new UserController().signup);
Remover método get da rota

2023-10-25 02:05 UTC, dairsposito commented on src/routes.ts
> +router.post('/signup', new UserController().signup);
O método signup da controller está estático agora, ajustar

2023-10-25 02:05 UTC, dairsposito commented on src/routes.ts
> +// Route for ping/pong testing
Remover comentário

2023-10-25 17:16 UTC, dairsposito requested changes

2023-10-25 17:16 UTC, dairsposito commented on src/service/UserService.ts
Esse arquivo não está atualizado conforme a develop. Realizar um pull da develop e mandar o PR novamente.

Arquivo atualizado da develop:
![image](https://github.com/matheus-yudi-newrizon/review-reveal-api/assets/37427121/bc2626e2-3cbd-44b7-9366-7bfe2d5bd02d)

2023-10-26 01:05 UTC, dairsposito approved these changes

2023-10-26 01:05 UTC, merged