feat: Adiciona JwtService para gerar tokens JWT
matheus-yudi-newrizon/review-reveal-api pull request #19
Opened 2023-10-30 02:54 UTC by raphaelhla

2023-10-30 03:15 UTC, raphaelhla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Configurar o JWT para gerar e retornar o token](https://trello.com/c/fOS4MHyy/421-configurar-o-jwt-para-gerar-e-retornar-o-token)

2023-10-31 02:11 UTC, dairsposito requested changes

2023-10-31 02:11 UTC, dairsposito commented on src/security/JwtService.ts
> +      throw new Error(); // criar exception personalizada para esse erro
Adicionar um TODO e já criar o card respectivo, colocando-o na descrição do TODO

2023-10-31 02:11 UTC, dairsposito commented on src/security/JwtService.ts
> +  private static readonly secretKey = 'secretKey';
Não deixar a secret key fixa no código

2023-11-01 01:41 UTC, dairsposito commented on src/security/JwtService.ts
> +    if (expiresIn) {
Pode utilizar um ternário aqui

2023-11-01 01:41 UTC, merged