Feature/rr 418 criar rota de login na usercontroller
matheus-yudi-newrizon/review-reveal-api pull request #24
Opened 2023-11-02 03:32 UTC by HebertFSoares

2023-11-02 03:33 UTC, HebertFSoares commented
![](https://github.trello.services/images/mini-trello-icon.png) [Criar rota/handler de login na UserController](https://trello.com/c/u64b2S9V/418-criar-rota-handler-de-login-na-usercontroller)

2023-11-07 01:19 UTC, dairsposito requested changes

2023-11-07 01:19 UTC, dairsposito commented on src/controller/UserController.ts
> +  public async login(req: Request, res: Response): Promise<void> {
Documentar o método de login com o swagger

2023-11-07 02:03 UTC, dairsposito requested changes

2023-11-07 02:03 UTC, dairsposito commented on src/controller/UserController.ts
> +   *       '401':
Ficou faltando o erro 500. Seria legal pensar uma forma de criar um template para os erros, para diminuir o tamanho das docs do swagger.

2023-11-08 01:35 UTC, dairsposito approved these changes

2023-11-08 01:35 UTC, merged