feat: Adiciona rota de redefinição de senha na userController
matheus-yudi-newrizon/review-reveal-api pull request #27
Opened 2023-11-07 23:29 UTC by raphaelhla

2023-11-08 01:42 UTC, dairsposito requested changes

2023-11-08 01:42 UTC, dairsposito commented on src/controller/UserController.ts
> +   *                   type: string
Ficou faltando o erro 500, seria legal dar uma olhada nos templates do swagger, para evitar repetição, principalmente na parte de erros.

2023-11-08 01:42 UTC, dairsposito commented on src/controller/UserController.ts
> +      const { email, token, password, confirmPassword } = req.body;
Creio que o email será recuperado através do token e não recebido no corpo da requisição

2023-11-08 01:42 UTC, dairsposito commented on src/service/UserService.ts
> +import { InvalidJwtTokenException, UserAlreadyExistsException } from '../exception';
A service que gera o token, não está utilizando JWT, logo há uma incompatibilidade. Verificar.

2023-11-08 18:45 UTC, rogeriofrsouza commented on src/controller/UserController.ts
> +      const { email, token, password, confirmPassword } = req.body;
Acho que no lugar do email entra o id

2023-11-09 02:27 UTC, dairsposito approved these changes

2023-11-09 02:27 UTC, merged