feat: implementação do cadastro de Usuario no UsuarioService
matheus-yudi-newrizon/review-reveal-api pull request #3
Opened 2023-10-19 00:26 UTC by raphaelhla

2023-10-19 00:27 UTC, raphaelhla commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BACK] Implementar lógica de cadastro na service](https://trello.com/c/gictMLZb/269-back-implementar-l%C3%B3gica-de-cadastro-na-service)

2023-10-19 17:37 UTC, dairsposito requested changes
Muito bom. Gostei da forma como o código está organizado.
Apenas documentar o método.

2023-10-19 17:37 UTC, dairsposito commented on src/service/UserService.ts
> +  public static async createUser(email: string, password: string): Promise<User> {
Documentar o método

2023-10-19 17:37 UTC, dairsposito commented on src/service/UserService.ts
> +    return this.userRepository.save(usuario);
O método save atualiza o usuário se o mesmo já existir no banco de dados. Se não existir, então ele insere. Seria esse o comportamento esperado pelo método?

2023-10-19 19:41 UTC, raphaelhla commented on src/service/UserService.ts
> +    return this.userRepository.save(usuario);
Sim esse é o comportamento esperado.

2023-10-20 17:15 UTC, dairsposito approved these changes

2023-10-20 17:15 UTC, merged