feat: Redefinicao de senha
matheus-yudi-newrizon/review-reveal-api pull request #30
Opened 2023-11-09 06:00 UTC by raphaelhla

2023-11-09 06:01 UTC, raphaelhla commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BACK] Checklist - Redefinição de senha](https://trello.com/c/Gi79C96t/405-back-checklist-redefini%C3%A7%C3%A3o-de-senha)

2023-11-09 17:40 UTC, dairsposito requested changes

2023-11-09 17:40 UTC, dairsposito commented on src/controller/UserController.ts
> +   * /signup:
A rota está incorreta e conflitando com a de signup: 
![image](https://github.com/matheus-yudi-newrizon/review-reveal-api/assets/37427121/1533dd2b-198f-45cf-8e4a-4635d3e63223)

2023-11-10 02:01 UTC, dairsposito approved these changes

2023-11-10 02:01 UTC, merged