Feature/rr 575 criar entidades da partida game review movie
matheus-yudi-newrizon/review-reveal-api pull request #33
Opened 2023-11-13 20:19 UTC by rogeriofrsouza

2023-11-13 20:19 UTC, rogeriofrsouza commented
![](https://github.trello.services/images/mini-trello-icon.png) [Criar entidades da Partida (game, review, movie)](https://trello.com/c/KICGidXx/575-criar-entidades-da-partida-game-review-movie)

2023-11-14 17:03 UTC, dairsposito requested changes

2023-11-14 17:03 UTC, dairsposito commented on __test__/mocks/Generate.ts
> +      score: 0,
Creio que no caso do maior score do usuário, record representa melhor.

2023-11-14 17:03 UTC, dairsposito commented on src/entity/GameReview.ts
> +}
Creio que seja legal adicionar os timestamps aqui, para saber quando a pessoa respondeu a pergunta.

2023-11-14 17:03 UTC, dairsposito commented on src/entity/User.ts
> +  score: number;
Mesma consideração apontada no arquivo de testes.

2023-11-14 17:15 UTC, rogeriofrsouza commented on __test__/mocks/Generate.ts
> +      score: 0,
A ideia seria mudar o nome pra record? Ou remover esse campo do User?

2023-11-14 17:16 UTC, rogeriofrsouza commented on __test__/mocks/Generate.ts
> +      score: 0,
Porque temos que guardar o score do Game e o score do User

2023-11-14 17:17 UTC, dairsposito commented on __test__/mocks/Generate.ts
> +      score: 0,
Alterar o nome para record

2023-11-14 17:36 UTC, dairsposito approved these changes

2023-11-14 17:36 UTC, merged