Alterar rota de login para verificar se tem uma partida ativa
matheus-yudi-newrizon/review-reveal-api pull request #35
Opened 2023-11-14 20:45 UTC by HebertFSoares

2023-11-14 20:45 UTC, HebertFSoares commented
![](https://github.trello.services/images/mini-trello-icon.png) [Alterar rota de login para verificar se tem uma partida ativa](https://trello.com/c/sTpF3TmC/610-alterar-rota-de-login-para-verificar-se-tem-uma-partida-ativa)

2023-11-15 01:15 UTC, dairsposito requested changes

2023-11-15 01:15 UTC, dairsposito commented on src/dto/LoginResponseDTO.ts
> +  game?: Game;
Adicionar uma linha em branco entre os parâmetros e o construtor.

2023-11-15 01:15 UTC, dairsposito commented on src/controller/UserController.ts
> +      if (loginResponse.id) {
O ideal é a que a controller não acesse a camada de dados, passando sempre pela service.

2023-11-15 01:15 UTC, dairsposito commented on src/controller/UserController.ts
> +    private readonly gameRepository: GameRepository
Não é uma boa prática, quando se trabalha com services, que a controller acesse a camada de dados.

2023-11-15 01:16 UTC, dairsposito commented
Sugiro atualizar a branch com a develop também, uma vez que o código da develop está mais atualizado.

2023-11-15 16:21 UTC, rogeriofrsouza commented on src/controller/UserController.ts
> -      if (rememberMe == null) throw new RequiredFieldException('rememberMe');
Não remover esta linha, nós precisamos dela na rota de login

2023-11-17 01:16 UTC, dairsposito approved these changes

2023-11-17 01:16 UTC, merged