PR: endpoint para buscar filmes por titulo
matheus-yudi-newrizon/review-reveal-api pull request #37
Opened 2023-11-16 23:30 UTC by NataliTrindade

2023-11-17 01:39 UTC, dairsposito requested changes

2023-11-17 01:39 UTC, dairsposito commented on src/repository/MovieRepository.ts
> +      return await this.ormRepository.findBy({ title: Like(`%${title}%`) });
Adicionar limite de filmes retornados

2023-11-17 01:39 UTC, dairsposito commented on src/controller/MovieController.ts
> +   *                   type: object
Não seria um array de filmes?

2023-11-18 03:24 UTC, rogeriofrsouza commented on src/controller/MovieController.ts
> +      const { title } = req.body;
Verificar se o title tem pelo menos 4 caracteres.

2023-11-18 03:25 UTC, rogeriofrsouza commented on src/repository/MovieRepository.ts
> +      return await this.ormRepository.findBy({ title: Like(`%${title}%`) });
Limite de 5

2023-11-18 03:27 UTC, rogeriofrsouza commented on src/service/MovieService.ts
> +    if (!filteredMovies) throw new MovieNotFoundException();
Trocar a expressão dentro do if. Verificar se o array está vazio.

2023-11-20 03:47 UTC, rogeriofrsouza commented on src/routes.ts
> +router.get('/movies/title', (req, res) => movieController.searchMovies(req, res));
Colocar o middleware validateJwt nesta rota, igual a rota: /games/new

2023-11-20 03:51 UTC, rogeriofrsouza commented on package.json
> +    "node-fetch": "^3.3.2",
Acredito que não precisamos desse node-fetch

2023-11-21 17:15 UTC, dairsposito requested changes

2023-11-21 17:15 UTC, dairsposito commented on src/controller/MovieController.ts
> +   *                 data:
O exemplo precisa retornar o tipo correto também, como array.

2023-11-22 09:47 UTC, dairsposito submitted a review, later dismissed

2023-11-22 09:48 UTC, dairsposito commented
Resolver os conflitos para então eu fazer o merge da branch

2023-11-22 14:25 UTC, rogeriofrsouza commented on src/repository/MovieRepository.ts
> +=======
Só faltou remover estas linhas 32 e 33

2023-11-22 14:25 UTC, rogeriofrsouza commented on src/repository/MovieRepository.ts
> +>>>>>>> 6d79fd84a46b2fa304c73fdd34c4546957dddbc1
E remover esta linha tbm

2023-11-23 01:35 UTC, dairsposito approved these changes

2023-11-23 01:35 UTC, merged