Feature/rr 577 endpoint para obter uma review
matheus-yudi-newrizon/review-reveal-api pull request #41
Opened 2023-11-20 21:27 UTC by rogeriofrsouza

2023-11-20 21:27 UTC, rogeriofrsouza commented
![](https://github.trello.services/images/mini-trello-icon.png) [Endpoint para obter uma review](https://trello.com/c/kXFs2DyB/577-endpoint-para-obter-uma-review)

2023-11-20 21:27 UTC, rogeriofrsouza commented
![](https://github.trello.services/images/mini-trello-icon.png) [Endpoint para obter uma review](https://trello.com/c/kXFs2DyB/577-endpoint-para-obter-uma-review)

2023-11-21 17:26 UTC, dairsposito requested changes

2023-11-21 17:26 UTC, dairsposito commented on src/service/ReviewService.ts
> +    let isRepeated: boolean;
Variável desnecessária. Você pode fazer a comparação direto na condicional do `do while`.
Recomendo olhar o Array.some() para fazer a condicional, talvez não seja preciso usar sequer o for dentro da estrutura `do while`.

2023-11-22 01:16 UTC, dairsposito approved these changes

2023-11-22 01:16 UTC, merged