Incrementar as quantidades de login
matheus-yudi-newrizon/review-reveal-api pull request #47
Opened 2023-11-23 20:24 UTC by HebertFSoares

2023-11-23 20:25 UTC, HebertFSoares commented
![](https://github.trello.services/images/mini-trello-icon.png) [Incrementar as quantidades de login e partidas conforme requisição](https://trello.com/c/OuEJT5zv/586-incrementar-as-quantidades-de-login-e-partidas-conforme-requisi%C3%A7%C3%A3o)

2023-11-24 01:21 UTC, dairsposito requested changes

2023-11-24 01:21 UTC, dairsposito commented on src/service/AuthService.ts
> +    user.loginCount = (user.loginCount || 0) + 1;
Usar o short aggregator

2023-11-24 01:21 UTC, dairsposito commented on src/entity/User.ts
> +  @Column({ default: 0 })
Implementar a contagem ou remover o campo

2023-11-24 21:03 UTC, dairsposito approved these changes

2023-11-24 21:03 UTC, merged