feat: altera funcionamento do método de geração aleatoria de review
matheus-yudi-newrizon/review-reveal-api pull request #54
Opened 2023-11-29 15:01 UTC by raphaelhla

Foi adicionado o atributo currentGameReview na entidade Game. Dessa forma é possivel retornar sempre a mesma review até que o usuário envie uma resposta, evitando que o usuário pule as reviews que ele não souber a resposta.

2023-11-29 15:01 UTC, raphaelhla commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BACK] Alterar rota de geração de review random](https://trello.com/c/RsSO087g/736-back-alterar-rota-de-gera%C3%A7%C3%A3o-de-review-random)

2023-11-30 01:07 UTC, dairsposito requested changes

2023-11-30 01:07 UTC, dairsposito commented on src/service/ReviewService.ts
> +  private async getUserById(userId: number): Promise<User> {
Esse método não deveria estar na service de usuário?

2023-11-30 01:07 UTC, dairsposito commented on src/service/ReviewService.ts
> +  private async getActiveGameByUser(user: User): Promise<Game> {
Esse método pertence a essa classe mesmo?

2023-11-30 02:06 UTC, dairsposito requested changes

2023-11-30 02:06 UTC, dairsposito commented on src/service/ReviewService.ts
> +    console.log('\nCurrent review tittle: ', review.movie.title);
Remover um t do `tittle`

2023-11-30 02:08 UTC, dairsposito approved these changes

2023-11-30 02:08 UTC, merged