Feature/rr 267 back criar rota controller para cadastro
matheus-yudi-newrizon/review-reveal-api pull request #6
Opened 2023-10-20 17:33 UTC by HebertFSoares

2023-10-20 17:33 UTC, HebertFSoares commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BACK] Criar rota/controller para cadastro do usuário](https://trello.com/c/ZkvoriNQ/267-back-criar-rota-controller-para-cadastro-do-usu%C3%A1rio)

2023-10-21 11:53 UTC, dairsposito requested changes

2023-10-21 11:53 UTC, dairsposito commented on docker-compose.yml
Esse arquivo já teve essas alterações comitadas na develop. Usar `git pull origin develop` e então fazer um push do PR novamente

2023-10-21 11:53 UTC, dairsposito commented on src/controller/CadastroController.ts
> +  async resposta(req: Request, res: Response) {
Documentar o método e alterar o nome para inglês

2023-10-21 11:53 UTC, dairsposito commented on src/controller/CadastroController.ts
> +export class CadastroController {
Alterar o nome da controller para inglês e deixar equivalente com a service também

2023-10-21 11:53 UTC, dairsposito commented on src/routes.ts
> +router.get('/user/cadastro', new CadastroController().resposta);
Alterar rota para inglês

2023-10-21 12:23 UTC, closed without merging