Implementar rota para pegar resposta do filme
matheus-yudi-newrizon/review-reveal-api pull request #67
Opened 2023-12-06 01:39 UTC by HebertFSoares

2023-12-06 01:40 UTC, HebertFSoares commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BACK] Criar rota para pegar resposta do filme](https://trello.com/c/dfGwDzIS/799-back-criar-rota-para-pegar-resposta-do-filme)

2023-12-06 01:45 UTC, dairsposito requested changes

2023-12-06 01:45 UTC, dairsposito commented on src/repository/MovieRepository.ts
> +   * Encontra filmes por uma determinada revisão.
Colocar os comentários em inglês, conforme padrão.

2023-12-06 01:45 UTC, dairsposito commented on src/service/MovieService.ts
> +  public async getMovieByReview(review: string): Promise<MovieDTO | null> {
Documentar o método

2023-12-06 01:58 UTC, rogeriofrsouza commented on src/controller/MovieController.ts
> +        throw new InsufficientLengthException('review', 1);
Essa exception será removida no PR https://github.com/matheus-yudi-newrizon/review-reveal-api/pull/68
Pode usar a [RequiredFieldException](https://github.com/matheus-yudi-newrizon/review-reveal-api/blob/develop/src/exception/RequiredFieldException.ts)

2023-12-06 02:05 UTC, rogeriofrsouza commented on src/repository/MovieRepository.ts
> +      if (!movie) {
Não precisa deste if aqui dentro, já tem o mesmo na Service hehe

2023-12-06 02:06 UTC, rogeriofrsouza commented on src/repository/MovieRepository.ts
> +import { FindOneOptions } from 'typeorm';
Este import não está sendo utilizado

2023-12-06 14:35 UTC, rogeriofrsouza commented on src/repository/MovieRepository.ts
> +      const movie: Movie | undefined = await this.ormRepository
Pode retornar direto o resultado do método igual nos outros métodos de Repository.

```return await this.ormRepository...```

2023-12-06 14:49 UTC, rogeriofrsouza commented on src/routes.ts
> +router.post('/movies/answer', validateJwt, (req, res) => movieController.getMovieByReview(req, res));
Podemos usar o método GET nesta rota, o que acha?

2023-12-06 14:57 UTC, rogeriofrsouza commented on src/controller/MovieController.ts
> +
Vamos adicionar o **Swagger-JSDoc** nesta rota também!
Vamos precisar validar uma palavra-chave enviada na requisição, se for uma rota GET ela vai vir pelo queryParam.
Temos um [middleware](https://github.com/matheus-yudi-newrizon/review-reveal-api/blob/develop/src/middleware/ValidateQuery.ts) pra verificar queryParam. Seguir este [exemplo](https://github.com/matheus-yudi-newrizon/review-reveal-api/blob/34933d2357aca6afcded5fcdc5ce651e1047f88d/src/routes.ts#L22).

2023-12-06 15:00 UTC, rogeriofrsouza commented on src/service/MovieService.ts
> +    try {
Não precisa do bloco try/catch na Service hehe

2023-12-07 02:21 UTC, dairsposito requested changes
Ficou faltando implementar a palavra chave, que será configurada no env da aplicação.

2023-12-08 01:35 UTC, dairsposito requested changes

2023-12-08 01:35 UTC, dairsposito commented on src/middleware/validateReview.ts
O middleware não está validando a palavra chave

2023-12-08 01:35 UTC, dairsposito commented on src/config/swagger.ts
A request não informa sobre a palavra chave

2023-12-08 23:01 UTC, dairsposito approved these changes
Aprovado, mas deixo como melhoria, pegar a resposta através do próprio game do usuário, sem a necessidade de receber o texto todo da review.

2023-12-08 23:01 UTC, merged