Feature/267 back criar rota controller do usuario
matheus-yudi-newrizon/review-reveal-api pull request #8
Opened 2023-10-23 03:56 UTC by HebertFSoares

2023-10-23 03:56 UTC, HebertFSoares commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BACK] Criar rota/controller para cadastro do usuário](https://trello.com/c/ZkvoriNQ/267-back-criar-rota-controller-para-cadastro-do-usu%C3%A1rio)

2023-10-23 17:00 UTC, dairsposito requested changes

2023-10-23 17:00 UTC, dairsposito commented on src/controller/UserController.ts
> +      res.status(201).json({ message: 'Usuário criado com sucesso', user: newUser });
Traduzir a mensagem para o inglês.

2023-10-23 17:00 UTC, dairsposito commented on src/controller/UserController.ts
> +      res.status(400).json({ error: 'Erro ao criar o usuário', details: error.message });
Traduzir a mensagem para o inglês.
O Raphael implementou os códigos de erro nas exceptions, acredito que seja importante não deixar fixo para retornar sempre 400 (bad request). As vezes, pode acontecer erro 500. Como fica nesse caso?
Da mesma forma, a mensagem também pode vir da exception (desde que esteja tratada na implementação da exception);

2023-10-24 01:11 UTC, dairsposito approved these changes

2023-10-24 01:11 UTC, merged