feat: corrigir user service
matheus-yudi-newrizon/review-reveal-api pull request #9
Opened 2023-10-24 04:39 UTC by raphaelhla

2023-10-24 04:45 UTC, raphaelhla commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BACK] Corrigir UserService](https://trello.com/c/wHhv8Lkf/329-back-corrigir-userservice)

2023-10-24 17:29 UTC, dairsposito requested changes
Todo @Types é útil apenas em desenvolvimento, não sendo necessário pesar o pacote de produção com essas dependências.
No demais, está muito bom o código. Parabéns!

2023-10-24 17:29 UTC, dairsposito commented on package.json
> +    "@types/bcrypt": "^5.0.1",
Instalar o types como dev dependencies

2023-10-25 01:23 UTC, dairsposito approved these changes

2023-10-25 01:23 UTC, merged